version: '3.8'

services:
  db:
    container_name: postgresql-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-root}
      POSTGRES_USER: ${DATABASE_USER:-root}
      POSTGRES_DB: ${DATABASE_NAME:-db}
    ports:
      - ${DATABASE_PORT:-5432}:5432
    env_file:
      - .env
    volumes:
      - ./.data/db:/var/lib/postgresql/data
